version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - aws cloudformation package --template-file search-gateway.yaml --s3-bucket prj2-codebuild-bucket --output-template-file gateway.yaml

artifacts:
  type: zip
  files:
    - search-gateway.yaml
    - gateway.yaml
